name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Specify your Java version here
          distribution: 'adopt' # You can also use 'temurin', 'zulu', etc.

      - name: Compile Java code
        run: |
          mvn clean compile # For Maven projects
          # or use
          # javac src/**/*.java # For simple Java projects without Maven

      - name: Run tests
        run: mvn test # If you're using Maven for testing
